homebrew_packages:
  - name: curl
  - name: fish
  - name: gh
  - name: ghq
  - name: gibo
  - name: git
  - name: github-nippou
  - name: hadolint
  - name: jq
  - name: mas
  - name: mise
  - name: peco
  - name: tig
  - name: tree
  - name: wget
homebrew_cask_packages:
  # browsers
  - name: google-chrome
  - name: arc
  # ime
  - name: google-japanese-ime
  # editor
  - name: cursor
  # communication tools
  - name: slack
  - name: zoom
  - name: notion
  - name: gather
  # utils
  - name: 1password
  - name: appcleaner
  - name: caffeine
  - name: clipy
  - name: deepl
  - name: figma
  - name: font-monaspace
  - name: ghostty
  - name: jordanbaird-ice
  - name: kap
  - name: karabiner-elements
  - name: logi-options+
  - name: meetingbar
  - name: rancher
  - name: rectangle
