homebrew_packages:
  - name: asdf
  - name: curl
  - name: fish
  - name: ghq
  - name: git
  - name: jq
  - name: mas
  - name: peco
  - name: tig
  - name: tree
  - name: wget
homebrew_cask_packages:
  # browsers
  - name: firefox
  - name: google-chrome
  # ime
  - name: google-japanese-ime
  # editor
  - name: visual-studio-code
  # communication tools
  - name: discord
  - name: slack
  - name: zoom
  - name: notion
  # utils
  - name: 1password
  - name: clipy
  - name: docker
  - name: iterm2
  - name: kap
  - name: karabiner-elements
  - name: deepl
  - name: spectacle
  - name: appcleaner
