---
- name: Setup my OSX
  hosts: localhost
  connection: local
  roles:
    - { role: macos, tags: ["macos"] }
    - { role: homebrew, tags: ["homebrew"] }
    - { role: git, tags: ["git"] }
    - { role: fish, tags: ["fish"] }
