# brew install
- name: setup homebrew
  ignore_errors: yes
  block:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: homebrew cask packages install
      community.general.homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
