# brew install
- name: setup homebrew
  block:
    - name: homebrew update
      homebrew:
        update_homebrew: true

    - name: homebrew packages install
      homebrew:
        name: '{{ homebrew_packages | map(attribute="name") | list }}'
        state: present
      when: homebrew_packages | length > 0

    - name: homebrew cask packages install
      community.general.homebrew_cask:
        name: '{{ homebrew_cask_packages | map(attribute="name") | list }}'
        state: present
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      when: homebrew_cask_packages | length > 0
  rescue:
    - name: Display homebrew error
      debug:
        msg: "Homebrewのインストールに失敗しました。詳細: {{ ansible_failed_result }}"
