---
# brew tap
- name: brew tap
  homebrew_tap: tap={{ item }} state=present
  with_items: '{{ homebrew_taps }}'
# brew update
- name: brew update
  homebrew: update_homebrew=yes
# brew install
- name: install brew package
  homebrew: >
    name={{ item.name }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: '{{ homebrew_packages }}'
  register: brew_result
# brew cask install
- name: install cask package
  homebrew_cask: name={{ item.name }} state={{ item.state | default('installed') }}
  with_items: '{{ homebrew_cask_packages }}'
  register: cask_result